### ISSUE TITLE
Regression on latest commit - alt+keys stop working

### ISSUE THREAD

**Issue by atweiden** [drmikehenry/vim-fixkey#16]
Reverting [454c19d1274679a8b34b7fe9bda18cae90852431](https://github.com/drmikehenry/vim-fixkey/commit/454c19d1274679a8b34b7fe9bda18cae90852431) fixes keybindings for me. I haven’t investigated why.

**Comment by drmikehenry** [comment]
Thanks for the additional details.  It turns out that the `TermResponse` autocmd is not sent for all terminals (notably not for tmux, PuTTY, and Linux console).  I've released version 0.3.15 which uses the `VimEnter` autocmd as a fallback to ensure that Fixkey setup runs in all cases.

**Comment by atweiden** [comment]
Tyvm.
