### ISSUE TITLE
Support TERM=tmux

### ISSUE THREAD

**Issue by atweiden** [drmikehenry/vim-fixkey#5]
There's a new $TERM / terminfo for tmux (tmux / tmux-256color), see: https://github.com/tmux/tmux/commit/7382ba82c5b366be84ca55c7842426bcf3d1f521

I'm using it to fix vim markdown italics when running in tmux. Could fixkey support this new TERM?

```
diff --git a/plugin/fixkey.vim b/plugin/fixkey.vim
index a52491b..8ff7cc0 100644
--- a/plugin/fixkey.vim
+++ b/plugin/fixkey.vim
@@ -586,6 +586,9 @@ elseif $TERM =~# '^rxvt\(-unicode\)\?\(-\d*color\)\?$'
 elseif $TERM =~# '\v^screen(-\d*color|-bce|-it|-s)*$'
     call Fixkey_setScreenKeys()
 
+elseif $TERM =~# '\v^tmux(-\d*color|-bce|-it|-s)*$'
+    call Fixkey_setScreenKeys()
+
 else
     let g:Fixkey_termType = "unknown"
 endif
```

**Comment by drmikehenry** [comment]
Let me look into it.  I haven't looked at the new version of tmux yet, but based on your patch it looks like it will be straightforward (presumably tmux still sends all the same escape sequences for keys when using TERM=tmux).  Thanks for the suggestion :-)

**Comment by drmikehenry** [comment]
I've uploaded v0.3.6 to detect TERM=tmux.

**Comment by atweiden** [comment]
ty

**Comment by drmikehenry** [comment]
You're welcome :-)
